# These are supported funding model platforms

Supports Me For Coffee !: https://github.com/likhonsible/DonationCrypto
Telegram : https://t.me/likhonsible
Twitter : https://t.me/likhonsible
Ko-fi: https://ko-fi.com/likhonsible
